In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

In [4]:
data = load_iris()

In [5]:
x = data.data
y = data.target

**Logistic Regression**


In [6]:
lr_score = cross_val_score(LogisticRegression(),x,y)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [7]:
lr_score

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [8]:
lr_score = np.average(lr_score)
lr_score

0.9733333333333334

**Decision Tree**

In [10]:
Dt_score = cross_val_score(DecisionTreeClassifier(),x,y)

In [11]:
Dt_score

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [12]:
Dt_score = np.average(Dt_score)

In [13]:
Dt_score

0.9666666666666668

**Support Vector Machine**

In [16]:
svc_score = cross_val_score(SVC(),x,y)

In [17]:
svc_score

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [18]:
svc_score = np.average(svc_score)

In [19]:
svc_score

0.9666666666666666

***From above score we could find the best model***




As in above case Logistic Regression has high accuracy so it is the best model for iris_data