In [5]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [6]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [7]:
one_hot("amazing restaurant",30)

[15, 25]

In [8]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[2, 27], [15, 25], [6, 12], [1, 21, 23], [20, 24, 8], [21, 27], [8, 24, 24], [14, 28], [14, 26], [26, 3]]


In [9]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[ 2 27  0  0]
 [15 25  0  0]
 [ 6 12  0  0]
 [ 1 21 23  0]
 [20 24  8  0]
 [21 27  0  0]
 [ 8 24 24  0]
 [14 28  0  0]
 [14 26  0  0]
 [26  3  0  0]]


In [10]:
embeded_vector_size = 5
model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [11]:
X = padded_reviews
y = sentiment

In [12]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 4, 5)              150       
_________________________________________________________________
flatten (Flatten)            (None, 20)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 21        
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________
None


In [13]:
model.fit(X, y, epochs=50, verbose=0)

In [14]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 125ms/step - loss: 0.6241 - accuracy: 1.0000


1.0

In [15]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [16]:
weights[16]

array([ 0.04929466,  0.04055515, -0.00869939,  0.03385606, -0.00157385],
      dtype=float32)

In [17]:
weights[4]

array([-0.04036378, -0.04259104,  0.03533361, -0.02768309, -0.01611924],
      dtype=float32)